export const contacts = {
  admin: [
    {
      id: 1,
      name: "John Doe",
      email: "john@example.com",
      phone: "123-456-7890",
    },
    {
      id: 2,
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "987-654-3210",
    },
    {
      id: 3,
      name: "Michael Johnson",
      email: "michael@example.com",
      phone: "555-123-4567",
    },
    {
      id: 4,
      name: "Emily Wilson",
      email: "emily@example.com",
      phone: "777-999-8888",
    },
    {
      id: 5,
      name: "David Brown",
      email: "david@example.com",
      phone: "555-987-6543",
    },
    {
      id: 6,
      name: "Sarah Lee",
      email: "sarah@example.com",
      phone: "888-777-5555",
    },
    {
      id: 7,
      name: "Robert Davis",
      email: "robert@example.com",
      phone: "123-555-7890",
    },
    {
      id: 8,
      name: "Jennifer Taylor",
      email: "jennifer@example.com",
      phone: "987-555-3210",
    },
    {
      id: 9,
      name: "William White",
      email: "william@example.com",
      phone: "555-123-4567",
    },
    {
      id: 10,
      name: "Mary Johnson",
      email: "mary@example.com",
      phone: "777-555-8888",
    },
    {
      id: 11,
      name: "James Smith",
      email: "james@example.com",
      phone: "555-987-6543",
    },
    {
      id: 12,
      name: "Karen Davis",
      email: "karen@example.com",
      phone: "888-555-5555",
    },
    {
      id: 13,
      name: "Daniel Lee",
      email: "daniel@example.com",
      phone: "123-555-7890",
    },
    {
      id: 14,
      name: "Lisa Taylor",
      email: "lisa@example.com",
      phone: "987-555-3210",
    },
    {
      id: 15,
      name: "Christopher White",
      email: "christopher@example.com",
      phone: "555-123-4567",
    },
    {
      id: 16,
      name: "Patricia Johnson",
      email: "patricia@example.com",
      phone: "777-555-8888",
    },
    {
      id: 17,
      name: "Joseph Smith",
      email: "joseph@example.com",
      phone: "555-987-6543",
    },
    {
      id: 18,
      name: "Nancy Davis",
      email: "nancy@example.com",
      phone: "888-555-5555",
    },
    {
      id: 19,
      name: "Elizabeth Lee",
      email: "elizabeth@example.com",
      phone: "123-555-7890",
    },
    {
      id: 20,
      name: "Thomas Taylor",
      email: "thomas@example.com",
      phone: "987-555-3210",
    },
  ],
  someRandomUser: [
    {
      id: 1,
      name: "Alice Johnson",
      email: "alice@example.com",
      phone: "111-222-3333",
    },
    {
      id: 2,
      name: "Bob Smith",
      email: "bob@example.com",
      phone: "444-555-6666",
    },
    {
      id: 3,
      name: "Eva Wilson",
      email: "eva@example.com",
      phone: "777-888-9999",
    },
    {
      id: 4,
      name: "Jack Davis",
      email: "jack@example.com",
      phone: "333-222-1111",
    },
    {
      id: 5,
      name: "Olivia Taylor",
      email: "olivia@example.com",
      phone: "999-888-7777",
    },
    {
      id: 6,
      name: "Charlie Lee",
      email: "charlie@example.com",
      phone: "222-333-4444",
    },
    {
      id: 7,
      name: "Grace White",
      email: "grace@example.com",
      phone: "888-777-6666",
    },
    {
      id: 8,
      name: "Daniel Brown",
      email: "daniel@example.com",
      phone: "444-555-6666",
    },
    {
      id: 9,
      name: "Sophia Davis",
      email: "sophia@example.com",
      phone: "111-222-3333",
    },
    {
      id: 10,
      name: "Mia Smith",
      email: "mia@example.com",
      phone: "555-666-7777",
    },
    {
      id: 11,
      name: "Noah Lee",
      email: "noah@example.com",
      phone: "777-888-9999",
    },
    {
      id: 12,
      name: "Liam Johnson",
      email: "liam@example.com",
      phone: "333-222-1111",
    },
    {
      id: 13,
      name: "Ava Wilson",
      email: "ava@example.com",
      phone: "999-888-7777",
    },
    {
      id: 14,
      name: "Emma Taylor",
      email: "emma@example.com",
      phone: "222-333-4444",
    },
    {
      id: 15,
      name: "Lucas White",
      email: "lucas@example.com",
      phone: "888-777-6666",
    },
    {
      id: 16,
      name: "Lily Brown",
      email: "lily@example.com",
      phone: "444-555-6666",
    },
    {
      id: 17,
      name: "James Davis",
      email: "james@example.com",
      phone: "111-222-3333",
    },
    {
      id: 18,
      name: "Ella Smith",
      email: "ella@example.com",
      phone: "555-666-7777",
    },
    {
      id: 19,
      name: "Alexander Lee",
      email: "alexander@example.com",
      phone: "777-888-9999",
    },
    {
      id: 20,
      name: "Liam Johnson",
      email: "liam@example.com",
      phone: "333-222-1111",
    },
  ],
};
